.eslintrc
.github/workflows/npm-publish.yml
README.md
jest.config.js
package-lock.json
package.json
src/CqlLibrary.ts
src/MeasureScoring.ts
src/__tests__/CqlLibrary.test.ts
src/__tests__/Measure.test.ts
src/__tests__/MeasurePopulation.test.ts
src/__tests__/MeasureScoring.test.ts
src/__tests__/Model.test.ts
src/__tests__/TestCase.test.ts
src/index.ts

Summary: Added Cql Library Model

added Cql Library model

---

package-lock.json
package.json
src/TestCase.ts

Remove actual value from TestCase group population and add new Display version that contains

Release 1.0.4

---

src/Measure.ts

[MAT-4429](https://jira.cms.gov/browse/MAT-4429)

Adding properties for MAT-4429

---

package-lock.json
package.json

This is breaking change. So updating minor version

MAT-4427 minor version upgrade

---

package.json
src/Measure.ts

https://jira.cms.gov/browse/MAT-4500

Added populationBasis field for Group

---

package-lock.json
package.json
src/Measure.ts

Release 1.1.1

---

package-lock.json
package.json
src/index.ts

[MAT-4525](https://jira.cms.gov/browse/MAT-4525)

update version number and add export for AggregateFunction

---

package-lock.json
package.json
src/TestCase.ts

Validate modified test case JSON before execution - [MAT-4401](https://jira.cms.gov/browse/MAT-4401)

add successful flag to outcome

---

package-lock.json
package.json
src/Measure.ts

MAT-4645: Add acl to measure

---

src/TestCase.ts
src/__tests__/TestCase.test.ts

Mat-4425: changed the property name

changed the property name

---

package.json
src/AggregateFunctionType.ts
src/TestCase.ts
src/__tests__/TestCase.test.ts

updated drop down list for aggregate function

updated drop down list for aggregate function

---

README.md
package.json
src/Population.ts

Adding a new type to PopulationTypes to support MeasurePopulationObservations

Release 1.3.2

---

package-lock.json
package.json
src/Measure.ts

Add optional description to MeasureObservation

Release 1.3.10

---

package-lock.json
package.json
src/CqlLibrary.ts
src/ProgramUseContext.ts
src/index.ts

[MAT-5430](https://jira.cms.gov/browse/MAT-5430)

add ProgramUseContext model, and add field for this to CqlLibrary

---

package-lock.json
package.json
src/Measure.ts
src/Organization.ts

Release 1.3.15

---

package-lock.json
package.json
src/Measure.ts

https://jira.cms.gov/browse/MAT-5536

Adding Patient Basis field to Measure Object

---

package-lock.json
package.json
src/Measure.ts

https://jira.cms.gov/browse/MAT-5668

MAT-5668: Add measureset to front end models

---

package-lock.json
package.json
src/CqlLibrary.ts
src/__tests__/CqlLibrary.test.ts

This PR deprecates CQLLibrary.groupID

Release 1.3.28

---

package-lock.json
package.json
src/BaseConfigurationTypes.ts

updated measure type list options

Release 1.3.31

---

package-lock.json
package.json
src/Stratification.ts

Jira Ticket: [MAT-6295](https://jira.cms.gov/browse/MAT-6295)(Optional) Related Tickets:
This PR adds a type for expected values to track.
*  Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
*  The tests appropriately test the new code, including edge cases
*  If you have any concerns they are brought up either to the developer assigned, security engineer, or leads

Release 1.3.35

---

package-lock.json
package.json
src/Stratification.ts
src/TestCase.ts

Fix stratification expectedValue reference from Stratification

Release 1.3.36

---

.github/workflows/npm-publish.yml
.github/workflows/unit_test_coverage.yml

Jira Ticket: [MAT-6310](https://jira.cms.gov/browse/MAT-6310)
NPM Audit Fix and update Actions to Node 20.x
*  Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
*  The tests appropriately test the new code, including edge cases
*  If you have any concerns they are brought up either to the developer assigned, security engineer, or leads

Dependency + node 20.x update

---

package-lock.json
package.json
src/Measure.ts

MAT-6167: Add optional key on measureMetaData for QDMMeasureDefinitions

Release 1.3.37

---

.gitignore
package-lock.json
package.json
src/Measure.ts

Reverts MeasureAuthoringTool/madie-models#193

Reverts previous merge, so that I can add keyword to publish the new version to NPM

---

package-lock.json
package.json
src/Measure.ts

MAT-6489 Adding ID for measureDefinition object

Release 1.3.41

---

package-lock.json
package.json
src/Measure.ts

MAT-6675/add cms id to the measureset

---

src/Model.ts
src/Stratification.ts
src/__tests__/CqlLibrary.test.ts

changed title of the PR to test auto publish

Release 1.3.42

---

package-lock.json
package.json

Jira Ticket: [MAT-6722](https://jira.cms.gov/browse/MAT-6722)
- publish v1.3.43

Release 1.3.43

---

package-lock.json
package.json
src/Measure.ts

Release 1.3.45

---

package-lock.json
package.json
src/Measure.ts

Jira Ticket: [MAT-6735](https://jira.cms.gov/browse/MAT-6735)
1. isManifestExpansion is a config option for test case execution.
2. If isManifestExpansion is false, then we fetch Latest expansions for ValueSets
3. If isManifestExpansion is true, then user will specify which manifest to use ( we need a new model for that )
*  If you have any …

Release 1.3.46

---

package-lock.json
package.json
src/TestCaseExcelExportDto.ts

Jira Ticket: [MAT-6728](https://jira.cms.gov/browse/MAT-6728)

Release 1.3.48

---

package-lock.json
package.json
src/TestCaseExcelExportDto.ts
src/index.ts

Release 1.3.49

---

package.json
src/Measure.ts

Jira Ticket: [MAT-6823](https://jira.cms.gov/browse/MAT-6823)

Release 1.3.50 MAT-6823 QDM Improvement Notation text field

---

package-lock.json
package.json
src/TestCaseExcelExportDto.ts

Jira Ticket: [MAT-6819](https://jira.cms.gov/browse/MAT-6819)

Release 1.3.51

---

package-lock.json
package.json
src/Measure.ts
src/__tests__/Measure.test.ts

Jira Ticket: [MAT-6746](https://jira.cms.gov/browse/MAT-6746)

Release 1.4.0 MAT-6746 delete cms id from measure collection

---

package.json
src/Measure.ts

Jira Ticket: [MAT-6853](https://jira.cms.gov/browse/MAT-6853)

Release 1.4.1

---

package.json
src/Measure.ts

Jira Ticket: [MAT-6853](https://jira.cms.gov/browse/MAT-6853)

Release 1.4.2

---

package-lock.json
package.json
src/TestCase.ts

Jira Ticket: [MAT-7166](https://jira.cms.gov/browse/MAT-7166)
MAT-7166: update test case import model to include metadata for export/import

Release 1.4.4

---

package-lock.json
package.json
src/Measure.ts

Jira Ticket: [MAT-6921](https://jira.cms.gov/browse/MAT-6921)
MAT-6921 add isVersionIncluded flag

Release 1.4.5

---

package-lock.json
package.json
src/BaseConfigurationTypes.ts

Jira Ticket: [MAT-7279](https://jira.cms.gov/browse/MAT-7279)
updated measure type options in the UI

Release 1.4.7

---

package-lock.json
package.json
src/Measure.ts

Jira Ticket: [MAT-6506](https://jira.cms.gov/browse/MAT-6506)
clean up old SDE and RAV fields

Release 1.4.9

---

package-lock.json
package.json
src/Measure.ts

Release 1.4.10

---

package-lock.json
package.json
src/Measure.ts

Jira Ticket: [MAT-6468](https://jira.cms.gov/browse/MAT-6468)

Release 1.4.11

---

package-lock.json
package.json
src/CqlLibrary.ts
src/IncludedLibrary.ts
src/Measure.ts
src/__tests__/CqlLibrary.test.ts

Jira Ticket: [MAT-7060](https://jira.cms.gov/browse/MAT-7060)

Release 1.4.12

---

package-lock.json
package.json
src/BaseConfigurationTypes.ts

Jira Ticket: [MAT-7492](https://jira.cms.gov/browse/MAT-7492)

Release 1.4.13

---

package-lock.json
package.json
src/Model.ts

Jira Ticket: [MAT-7502](https://jira.cms.gov/browse/MAT-7502)

Release 1.4.14

---

package-lock.json
package.json
src/IncludedLibrary.ts

Jira Ticket: [MAT-7464](https://jira.cms.gov/browse/MAT-7464) Add alias to IncludeLibrary model

Release 1.4.15

---

package-lock.json
package.json
src/TestCase.ts

Jira Ticket: [MAT-7595](https://jira.cms.gov/browse/MAT-0000)

Release 1.4.16

---

package-lock.json
package.json
src/TestCase.ts

Jira Ticket: [MAT-7595](https://jira.cms.gov/browse/MAT-7595)

Release 1.4.17

---

package-lock.json
package.json
src/TestCase.ts

Jira Ticket: [MAT-7604](https://jira.cms.gov/browse/MAT-7604)

Release 1.4.18

---

package-lock.json
package.json
src/Measure.ts

MAT-7945 add improvement notation description to group
Jira Ticket: [MAT-7945](https://jira.cms.gov/browse/MAT-7945)

Release 1.4.19

---

package-lock.json
package.json

Jira Ticket: [MAT-7945](https://jira.cms.gov/browse/MAT-7945)

Release 1.4.20

---

package-lock.json
package.json

Release 1.2.22

---

package-lock.json
package.json
tsconfig.json

Release 1.4.23

---

package-lock.json
package.json
src/Measure.ts

Jira Ticket: [MAT-7529](https://jira.cms.gov/browse/MAT-7529) 
- remove unwanted model type allowed
- Added codeSystemUrl to code model

Release 1.4.24 

---

package-lock.json
package.json
src/Measure.ts

Jira Ticket: [MAT-8066](https://jira.cms.gov/browse/MAT-8066)
added intended venue porperty to measure meta data

Release 1.4.25

---

package-lock.json
package.json
src/Measure.ts

Jira Ticket: [MAT-8015](https://jira.cms.gov/browse/MAT-8015)

Release 1.4.26

---

package.json

Jira Ticket: [MAT-8015](https://jira.cms.gov/browse/MAT-8015)

Release 1.4.27

---

package-lock.json
package.json

Release 1.4.28

---

package-lock.json
package.json
src/Measure.ts

Jira Ticket: [MAT-6554](https://jira.cms.gov/browse/MAT-6554)

Release 1.4.29

---

package-lock.json
package.json

Jira Ticket: [MAT-8277](https://jira.cms.gov/browse/MAT-8277)
- **MAT-8277: Forgot to run tsc prior to publish. Re-do.**

Release 1.4.32

---

package-lock.json
package.json
src/Measure.ts

Release 1.4.33

---

package-lock.json
package.json
src/index.ts

Jira Ticket: [MAT-8383](https://jira.cms.gov/browse/MAT-8383)

Release 1.4.36

---

package-lock.json
package.json
src/TestCase.ts
src/__tests__/TestCase.test.ts

Jira Ticket: [MAT-8575](https://jira.cms.gov/browse/MAT-8575)

Release 1.4.37

---

package-lock.json
package.json
src/Model.ts

Release 1.4.38

---

package-lock.json
package.json
src/OwnershipType.ts
src/ViewScope.ts
src/index.ts

…ies, Shared Measures/Libraries, All Measures/Libraries) a user wants to view on the Measures/Libraries list page
Jira Ticket: [MAT-8024](https://jira.cms.gov/browse/MAT-8024)

Release 1.4.42
